@startuml
'https://plantuml.com/class-diagram

scale 1.2

class Slime

class Hero extends Character implements Runnable, Attackable{
    + int hp
    - String name

    attack(slime: Slime )
}

class SuperHero extends Hero

abstract class Character {
    {abstract} +attack(slime: Slime)
}

interface Attackable {
    {abstract} +attack(slime: Slime)
}

interface Runnable {
    {abstract} +run
}

@enduml