@startuml

interface Attackable {
    {abstract} +attack()
}

interface Runnable {
    {abstract} +run()
}

abstract class Character {
+ name: String
+ hp : Int

abstract attack(slime: Slime)

}


'class Slime


class Hero extends Character implements Runnable, Attackable {
+ hp: Int
- name: String

attack(slime: Slime)
}

'class SuperHero {}



@enduml