@startuml
'https://plantuml.com/class-diagram

class Slime


class Hero {
    + hp: Int
    - name: String

    attack(slime: Slime)
}

class SuperHero extends Hero

abstract class Character {
    {abstract} +attack()
}

@enduml