@startuml

abstract class Asset {
    +name: String
    +price: Int
}

abstract class TangibleAsset extends Asset {
    + name: String
    + price: Int
    + color: String
}

abstract class IntangibleAsset extends Asset {
    + name: String
    + price: Int
}

class Computer extends TangibleAsset {
    + name: String
    + price: Int
    + color: String
    + maker: String
}

class Book extends TangibleAsset {
    + name: String
    + price: Int
    + color: String
    + isbn: String
}

class Patent extends IntangibleAsset {
    + name: String
    + price: Int
    + patentNumber: String
}
@enduml